image: maven:latest

include:
  - template: Code-Quality.gitlab-ci.yml

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test 
  
code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
  
code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]

    
    